### ISSUE TITLE
Posting this I realize it's really old since this is the reason

### ISSUE THREAD

**Issue by cryptid11** [anoek/webrtc-group-chat-example#3]
I post this here anyway

It already says:

```
 node -e "var express = require('socket.io');"
(node:23046) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
```

and when I start the server:

```
node signaling-server.js
   info  - socket.io started
/home/cryptid11/node_modules/express/lib/express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/home/cryptid11/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/home/cryptid11/Documents/webrtc-group-chat-example/signaling-server.js:20:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

I'm trying to start from nothing with js so maybe I need to find something newer, the problem is nowadays you find only examples for webrtc where "wonderful" libraries that requires keys interface with the webrtc lib, I can't find anything easy to learn about only webrtc...

**Comment by anoek** [comment]
This should be fixed with #2 having been merged
